### ISSUE TITLE
explore extreme values of data

### ISSUE THREAD

**Issue by sdat2** [ai4er-cdt/flood_risk_shipston#1]
there aren't many python packages for doing this

**Comment by sdat2** [comment]
I will probably initially use https://github.com/sdat2/scikit-extremes to do the analysis. This only has Block-Maxima currently implemented in it (i.e I haven't managed to add Peak-over-Threshold).

**Comment by JoycelynLongdon** [comment]
**Work Stream Goals**

- [x] Understanding the seasonality of extreme flood events

- [ ] Building an extreme value distribution

- [ ] Determine whether there are flood basins (gauged) and their thresholds - so we can know 

- [ ] Create a multivariate extreme distribution between rainfall and the river height (generally in R)

**Comment by sdat2** [comment]
![bm-fit](https://user-images.githubusercontent.com/30407294/96477885-ee418900-122e-11eb-9ad3-48f8d27315de.png)

Block maxima fit for river height is terrible!

**Comment by sdat2** [comment]
useful looking package: https://github.com/iagolemos1/thresholdmodeling/tree/0.0.1

**Comment by sdat2** [comment]
![return-level-3m-threshold](https://user-images.githubusercontent.com/30407294/97108796-aa83cf00-16c7-11eb-985f-84c6a515edb2.png)
Used 3m threshold alongside stage 60 min data (filtered).  The non-independence of different values contributes to quite a bad fit; the top values all come from the large flood in 2007. [news article on floods](https://www.shipstontowncouncil.org/news-archive/ten-years-on-from-the-fearsome-floods-of-2007.html)

**Comment by sdat2** [comment]
![peaks-diff-thresholds](https://user-images.githubusercontent.com/30407294/97116501-79ba8e80-16f5-11eb-8c2e-21f110a4246b.png)

Looking at the different peaks that come out after using `scipy.find_peaks`, more reasonable as it doesn't pick up as many from the 2007 flood.

**Comment by Croydon-Brixton** [comment]
Project closed.
