### ISSUE TITLE
Find (& request for) other data sources

### ISSUE THREAD

**Issue by luke-scot** [ai4er-cdt/flood_risk_shipston#10]
- CEDA (various climate/environment datasets)
- LiDAR (topography)
- Historic rainfall
- Soil moisture
- Land Use:  UK gov land use registry/Aerial Photography
- Building since beginning of measurements?
- LSTM model data from US training (Seb)

**Comment by shmh40** [comment]
https://hess.copernicus.org/articles/23/5089/2019/hess-23-5089-2019.pdf

Table 4 (page 5102) of this paper contains the input features ranked by importance. It would be great to use their model to predict the flow rate etc of our system, either by training their LSTM with a subsection of our data, or by using their LSTM already pretrained on American basins (question of transferability here - anyone with transfer learning experience?).

So would like to identify data sources for these inputs.

**Comment by Croydon-Brixton** [comment]
From Marc's slack message

Data portals:
UK water resources portal: https://eip.ceh.ac.uk/hydrology/water-resources/ [No data for the area - Ira]
Centre for Environmental Data Analysis (CEDA): https://www.ceda.ac.uk/ 
Environment Agency data search portal: https://data.gov.uk/search?filters%5Bpublisher%5D=Environment+Agency
National River Flow Archive: https://nrfa.ceh.ac.uk/ [Similar data to Wisky but more coarse in time - Ira]
Other resources:
Google Earth Engine: https://earthengine.google.com/ [looking into it - Ira, Arduin]
QGIS software: https://qgis.org/en/site/

**Comment by luke-scot** [comment]
Data Wiki - https://github.com/ai4er-cdt/flood_risk_shipston/wiki/Data-Summary

**Comment by Croydon-Brixton** [comment]
Workflow todos:
For each datasource check 
- [ ] is it useful
- [ ] is it available around shipston
- [ ] can we easily get it
- [ ] download if all of the 3 above are satisfied

**Comment by Ira-Shokar** [comment]
National River Flow Archive:

Station: 54106 - Stour (Warks) at Shipston
Link: https://nrfa.ceh.ac.uk/data/station/info/54106

- [x] is it useful
- [x] is it available around shipston
- [x] can we easily get it
- [x] download if all of the 3 above are satisfied

After exploration the data is similar to the Wisky data but more course-  one measurement per day.

**Comment by shmh40** [comment]
Closed as this issue has been superseded by issues #17 and #18 which split the Shipston data we require into forcings and static attributes.
