### ISSUE TITLE
Train LSTM model on all 671 basins in CAMELS-GB dataset

### ISSUE THREAD

**Issue by shmh40** [ai4er-cdt/flood_risk_shipston#14]
Train LSTM model on all basins in the dataset - then use it to predict discharge in our Shipston basin.

To predict for the Shipston basin we need data specified in issues #17 and #18 . 

Then we can use this model to predict discharge of the river for 2019/20, and compare to the discharges observed (which will hopefully be smaller due to the natural flood defences!)

**Comment by herbiebradley** [comment]
Interested in helping with this since I've been reading the paper and notebook code. I was thinking I might convert the notebook into a set of Python files and maybe refactor it a bit, since that might make it easier to work with on JASMIN - unless you're already doing this?
