### ISSUE TITLE
create standard method for plotting flood catchment areas

### ISSUE THREAD

**Issue by sdat2** [ai4er-cdt/flood_risk_shipston#4]

**Comment by Croydon-Brixton** [comment]
Workstream points:
- [x] plot shipston catchment area
- [x] overlay asset data
- [x] overlay rainfall gauges
- [x] overlay river gauges
- [ ] overlay any other kind of data we have (e.g. vegetation/topology/..)
- [ ] ideally plot sub-basin boundaries based on watersheding from topology data
