### ISSUE TITLE
Find and add the missing 300 asset data

### ISSUE THREAD

**Issue by Croydon-Brixton** [ai4er-cdt/flood_risk_shipston#5]

**Comment by Croydon-Brixton** [comment]
Workstream todos
- [ ] ping oscar & ask for progress

**Comment by Croydon-Brixton** [comment]
Here's an analysis of their first 200 assets - once we have all we can simply rerun
[svm-1-asset-data-exploration.zip](https://github.com/ai4er-cdt/flood_risk_shipston/files/5377277/svm-1-asset-data-exploration.zip)

**Comment by sdat2** [comment]
This is done right?
