### ISSUE TITLE
Wiski Data Exploration

### ISSUE THREAD

**Issue by mataln** [ai4er-cdt/flood_risk_shipston#6]

**Comment by JoycelynLongdon** [comment]
Goals:

- [x] Explore rainfall data

- [x] Correlate with the flow data

**Comment by Croydon-Brixton** [comment]
Workstream todos:
- [x] Explore rainfall data
- [x] Correlate with flow data
- [x] Get # of flood events
- [x] Get patterns of flood events (when do they occur in a year? all time round? summer?, ..)
